RecMedia = RecMedia or {}

RecMedia["c2d1a7e8-35af-44e5-a639-fd88b7200f01"] = {
    itemDisplayName = "RM_c2d1a7e8-35af-44e5-a639-fd88b7200f01",
    title = "RM_c2d1a7e8-35af-44e5-a639-fd88b7200f01",
    subtitle = nil,
    author = "Peter Jackson",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[Gandalf arrives in the Shire.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "A wizard is never late, Frodo Baggins.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "He arrives precisely when he means to.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Bilbo at his birthday party.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I regret to announce, this is the end! I'm going now.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Bilbo prepares to leave the Shire.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I think I'm quite ready for another adventure.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Frodo inherits the Ring.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Keep it secret, keep it safe.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The Ringwraiths search for the Ring.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "They are the Nazgul. Neither living nor dead.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "They will never stop hunting you.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[At the Council of Elrond.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "One does not simply walk into Mordor.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "I will take the Ring, though I do not know the way.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[The Fellowship sets out from Rivendell.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Boromir struggles with temptation.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "It is a strange fate that we should suffer so much fear and doubt over so small a thing.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The Fellowship continues through Moria.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I wish the Ring had never come to me.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "So do all who live to see such times. But that is not for them to decide.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "All we have to decide is what to do with the time that is given to us.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Pippin drops a bucket, and a fight with Orcs and a Troll takes place!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Frodo is stabbed by the troll with a spear, and falls!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[The Fellowship defeats the troll and Frodo survives by his Mithril shirt!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS-2" },
        { text = "[A Running Battle in Moria occurs and then .. the Balrog comes!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "This is beyond any of you. Run!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[Through a harrowing hail of arrows and falling starways, the Fellowship flees!]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Gandalf stands alone at the Bridge of Khazad Dum!]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "You cannot pass! I am a servant of the Secret Fire, wielder of the flame of Anor!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[The Balrog howls in anger as its fiery whip is brandished from its shadow and strikes at Gandalf]", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[Gandalf absorbs the strike and defies its might!]", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "YOU! SHALL NOT! PASS!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "[Gandalf strikes the bridge and the Balrog of Morgoth falls, but so does Gandalf!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Gandalf falls into the abyss.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "Fly, you fools!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Aragorn leads the Fellowship after Gandalf's fall.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The Fellowship arrives in Lothlorien.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Frodo offers the ring to Galadriel, Lady of Light, and she refuses the temptation.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I pass the test, I will diminish, and go into the West, and remain Galadriel.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "Even the smallest person can change the course of the future.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[The Fellowship leave Lothlorien with gifts, Gimli with three strands of Galadriel's hair, a kingly gift.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Boromir tries to take the ring but Frodo gets away!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "What have I done? Frodo! Please! I'm Sorry!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN+1" },
        { text = "[The Uruk-hai of Isengard guard and the Fellowship is broken!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Boromir falls trying to save Merry and Pippin, and begins to die in front of Aragorn.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-1" },
        { text = "I would have followed you, my brother, my captain, my king.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Frodo leaves the Fellowship.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Sam follows Frodo across the river.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I made a promise, Mr. Frodo. 'Don't you leave him, Samwise Gamgee.'", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "And I don't mean to.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Frodo and Sam continue toward Mordor.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Aragorn, Gimli and Legolas honor Boromir, with Aragorn turning to the Three Hunters.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-1" },
        { text = "Let's hunt some Orc.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
    },
};

RecMedia["d2f4b7d9-42c1-49b2-a29a-1ad08c120f01"] = {
    itemDisplayName = "RM_d2f4b7d9-42c1-49b2-a29a-1ad08c120f01",
    title = "RM_d2f4b7d9-42c1-49b2-a29a-1ad08c120f01",
    subtitle = nil,
    author = "Peter Jackson",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[Gollum leads Frodo and Sam.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "We swears, to do what you wants. We swears on the Precious.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "You know the way to Mordor?", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Frodo and Sam debate Gollum's trust.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The Three Hunters pursue the Uruk-hai.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "They're taking the hobbits to Isengard!", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Aragorn meets Eomer and his riders.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "What business does an elf, a man, and a dwarf have in the Riddermark?", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "I am Aragorn, son of Arathorn. This is Gimli, son of Gloin, and Legolas, of the woodland realm.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "We are friends of Rohan, and of Theoden, your king.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Gollum catches rabbits.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "They are Tender they are nice!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Sam makes a stew out of the Rabbits.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "What we needs is a few good taters!", r = 0.6, g = 0.2, b = 0.4, codes = "COO+1" },
        { text = "What's taters Precious?", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "PO-TA-TOES! Boil em, Mash em, Stick em in a stew!", r = 0.6, g = 0.2, b = 0.4, codes = "COO+3" },
        { text = "[Saruman watches from Orthanc.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "The world is changing. Who now has the strength to stand against the armies of Isengard?", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Saruman shows Grima the army of Uruk-Hai.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+3" },
        { text = "[Faramir captures Frodo and Sam.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "The Ring will go to Gondor.", r = 0.2, g = 0.6, b = 0.4, codes = "STS+1" },
        { text = "[The Ents hold council in Fangorn with Merry and Pippin.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "We have decided. You are not Orcs.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "[Helm's Deep is under siege, the ten thousand Uruk-Hai attack in a dark storm!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "So it begins.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Gimli and Legolas start keeping score of their kills.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Legolas! Two Already!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "I'm on Seventeen!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "WHA?!? I'll have no Pointy Ear Outscoring me!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-5" },
        { text = "[The Deepening Wall is breached by explosives with a cataclysmic BOOM and THUNDER!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Aragorn! Fall back to the Keep! Get your Men out of there!", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[The Hornburg is about to be breached. Theoden and Aragorn speak as the gates are attacked.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "So much Death . . . What can men do against such reckless hate?", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "Ride out with me. Ride out and meet them.", r = 0.6, g = 0.2, b = 0.4, codes = "STS-1" },
        { text = "For Death and Glory?", r = 0.6, g = 0.2, b = 0.4, codes = "STS-1" },
        { text = "For Rohan, for your people.", r = 0.6, g = 0.2, b = 0.4, codes = "STS-1" },
        { text = "Yes ... Yes. The horn of Helm Hammerhand shall sound in the deep! One last time!", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "Let this hour, that we draw swords together!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-1" },
        { text = "Fell deeds awake. Now for wrath, now for ruin, and the Red Dawn!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-2" },
        { text = "[The gates of the Hornburg fall to the Uruk-Hai's battering ram!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "[The King and the last of his guard with Aragorn charge out of the gates!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS-4" },
        { text = "Forth, Eorlingas!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-5" },
        { text = "[Gandalf arrives with the Rohirrim, and the Uruk-hai route!]", r = 0.0, g = 0.7, b = 0.3, codes = "STS-5" },
        { text = "[The battle at Helm's Deep ends.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-5" },
        { text = "Victory! We have victory!", r = 0.6, g = 0.2, b = 0.4, codes = "STS-5" },
        { text = "The battle for Helm's Deep is over; the battle for Middle-earth is about to begin.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The Ents and Merry and Pippin march on Isengard.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Break the dam. Release the river!", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Treebeard guides the ents in their fury to break the dam!]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Saruman watches from Isengard helpless as Isengard is flooded.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[In Osgiliath, Frodo is almost taken by a winged Nazgul]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+10" },
        { text = "[Sam comforts Frodo after he saves Frodo.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-1" },
        { text = "I can't do this Sam.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "I know. It's all wrong. By rights we shouldn't even be here. But we are.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "It's like in the great stories, Mr. Frodo. The ones that really mattered.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "How could the world go back to the way it was when so much bad had happened?", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "But in the end, it's only a passing thing, this shadow. Even darkness must pass.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "Those were the stories that stayed with you. That meant something, even if you were too small to understand why.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "Folk in those stories had lots of chances of turning back, only they didn't.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "They kept going, because they were holding on to something.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "What are we holding onto Sam?", r = 0.6, g = 0.2, b = 0.4, codes = "STR-1" },
        { text = "There is some good in this world, Mr. Frodo, and it's worth fighting for.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-5 PAN-5 STS-5" },
        { text = "[Frodo debates with Faramir.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I think at last, we understand one another, Frodo Baggins.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[One of Faramir's officers speaks up]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "You know the laws of our country, the laws of your father. If you let them go your life will be forfeit.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "Then it is forfeit. Release them.", r = 0.6, g = 0.2, b = 0.4, codes = "STS-2" },
        { text = "[Gollum plots his revenge.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "They stole it from us. Sneaky little hobbitses.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Gollum speaks to himself.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "We could let her do it ... This way Hobbitses!", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
    },
};

RecMedia["e3b6a7c3-43d5-4a28-bf3a-3ab9e9b3b7c7"] = {
    itemDisplayName = "RM_e3b6a7c3-43d5-4a28-bf3a-3ab9e9b3b7c7",
    title = "RM_e3b6a7c3-43d5-4a28-bf3a-3ab9e9b3b7c7",
    subtitle = nil,
    author = "Peter Jackson",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[Gandalf, Theoden, Aragorn, Legolas, and Gimli ride into the ruins of Isengard through Fanghorn forest, towards laughter.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Pippin and Merry relax on the walls of the ruined Numenorean fort, smoking.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I feel like I am back at the Green Dragon. A mug in my hand, putting my feet up on a settle after a hard day's work.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "Only, you've never done a hard day's work.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Merry and Pippin share a laugh and chuckle as they smoke and munch on salted pork, before warmly welcoming Gandalf and company.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Welcome, my lords! To Isengard!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Gimli then calls out to them from the horse of Legolas.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "You young rascals! A merry hunt you've led us on, and now we find ya feasting . . . and smoking!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "We are sitting on a field of victory, enjoying a few well-earned comforts. The salted pork is -particularly- good.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Gimli then pauses and merely repeats two words.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Salted pork?", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Gandalf sighs and shakes his head.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Hobbits . . .", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[After meeting with Treebeard, they speak to the traitor Saruman, who is killed by Grima. Legolas shoots Grima, and Saruman falls to his death.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+5" },
        { text = "[Treebeard the Ent shakes his head.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "The filth of Saruman is washing away . . .", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Pippin sees a Palantir, a lost seeing stone in the waters of Isengard. Gandalf quickly takes it from Pippin before he can be affected.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The victors of Helm's Deep hold a feast to celebrate their victory. King Theoden raises a toast to all present.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Tonight we remember those who gave their blood to defend this country. Hail the Victorious Dead!", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The hall hails their king, and merriment commences throughout the halls, with calls for 'Victory' and then drinking games, in which Gimli and Legolas partake.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Gimli may have won the competition for the most kills at Helm's Deep, but he falters and stumbles over drunk as Legolas remains standing.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Game over.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Pippin sneaks a look into the Palantir as Gandalf sleeps after the feast, and the Eye of Sauron sees him. Aragorn briefly holds it too before Gandalf hides it.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+10" },
        { text = "[Pippin and Merry are separated for the first time, as Merry stays in Rohan and Pippin, now sought by the Great Enemy, is taken by Gandalf on Shadowfax to Minas Tirith.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Gandalf and Pippin journey through dark forests and shallow streams, while white mountains tower in the background.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "We just passed into the realm of Gondor!", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Finally, they behold the ringed capital city of Gondor, with its White Spire jutting from the center like a white cliff.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Minas Tirith, city of Kings.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[The duo race up the cobbled streets of the seven rings of Minas Tirith, reaching the top of the city to meet the Steward of Gondor, Denethor.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Gandalf and Pippin enter the great hall of Denethor.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Denethor, father of Boromir, holds his eldest son's broken horn, cleaved in half, in grief. Pippin offers his servitude, while Gandalf tries to focus on the matter at hand.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Pippin pledges his loyalty to Gondor as repayment, kneeling before Denethor.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "You are here to take my son's place. To guard my city.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Gandalf tries to focus on the matter at hand.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "My lord, there will be a time to grieve for Boromir, but it is not now. War is coming; the enemy is on your doorstep. Where are Gondor's armies?", r = 0.2, g = 0.6, b = 0.4, codes = "PAN+1" },
        { text = "You still have friends; you are not alone in this fight. Send word to Theoden of Rohan; light the beacons.", r = 0.2, g = 0.6, b = 0.4, codes = "STS+2" },
        { text = "[Denethor glares at Gandalf and responds coldly.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+2" },
        { text = "You think you are wise, Mithrandir? Yet for all your subtleties, you have not wisdom.", r = 0.2, g = 0.6, b = 0.4, codes = "PAN+2" },
        { text = "With your left hand, you would use me as a shield against Mordor, and with your right, you seek to supplant me. I know who rides with Theoden of Rohan.", r = 0.2, g = 0.6, b = 0.4, codes = "PAN+2" },
        { text = "Oh yes, word has reached my ears of this Aragorn, son of Arathorn. And I will tell you now: I will -not- bow to this Ranger from the North!", r = 0.2, g = 0.6, b = 0.4, codes = "STS+3" },
        { text = "[Gandalf then speaks firmly.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "Authority is not given to you to deny the Return of the King, Steward of Gondor.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+2" },
        { text = "[Denethor glares coldly.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "The rule of Gondor is mine! And NO others!", r = 0.2, g = 0.6, b = 0.4, codes = "STS+4" },
        { text = "[Gandalf leaves with Pippin in disgust.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "All has turned to vain ambition; he would even use his grief as a cloak!", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Gandalf helps Pippin to light the beacons of Minas Tirith, setting off a chorus as the beacons are lit across all of Gondor.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS-5" },
        { text = "Hope is kindled . . .", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-5" },
        { text = "[Aragorn, Legolas, and Gimli rally with King Theoden upon seeing the beacons lit. Elrond approaches.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "The beacons are lit. Gondor calls for aid.", r = 0.2, g = 0.6, b = 0.4, codes = "STS-1" },
        { text = "And Rohan will answer! Muster the Rohirrim!", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[Elrond arrives and offers Aragorn Andúril, Flame of the West, reforged from the shards of Narsil.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "Become the man you were born to be.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "Become the man who you were born to be.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Pippin and Gandalf watch as the orcs march towards Minas Tirith.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "It's so quiet ...", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+2" },
        { text = "It's the deep breath before the plunge", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+2" },
        { text = "Is there any hope, Gandalf? For Frodo and Sam?", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "There never was much hope, just a fool's hope.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-1" },
        { text = "[The Siege begins, with heads of slain Gondorians flung into the city, followed by large stones! Denethor, seeing his fallen son Faramir, is brought low by Nazgul shrieks!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "Abandon your posts! FLEE! FLEE FOR YOUR LIVES!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+2" },
        { text = "[The people of Minas Tirith panic as soldiers begin to flee. Denethor staggers at the sight of Mordor's hosts and quivers in fear.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Gandalf promptly confronts the Steward of Gondor, knocking him out and rallying the soldiers of Minas Tirith!]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Prepare for battle! Courage is the best defense that you have now.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[The first assault on the city begins as orcs launch stones and fire.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Hold them back! Do not give in to fear!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+2" },
        { text = "[The battering ram Grond is brought forth to breach the city gate.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Grond! Grond!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "[The gate falls, and the city begins to crumble!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Gandalf and Pippin fall back with the defenders to one of the upper levels as the lower city of Minas Tirith burns.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "I didn't think it would end this way.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "End? No, the journey doesn't end here. Death is just another path, one that we all must take.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-3" },
        { text = "The grey rain-curtain of this world rolls back, and all turns to silver glass, and then you see it.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "What? Gandalf? See what?", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-3" },
        { text = "White shores, and beyond . . . a far green country, under a swift sunrise.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "Well . . . that isn't so bad.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-3" },
        { text = "No . . . No, it isn't.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "[The gate buckles from a troll's hammer, and the defenders make ready for what comes.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[But then at dawn, the Rohirrim arrive at Minas Tirith at dawn, horns blaring across the plains with Theoden at its head as he gives commands!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Arise! Arise, riders of Theoden!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "Spears shall be shaken! Shields shall be splintered!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "A Sword Day! A Red Day! Ere the Sun Rises!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "[Merry, hidden with Eowyn, clings to her for the coming storm.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Whatever happens, stay with me. I'll look after you.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-3" },
        { text = "[The Riders lower their lances, and Theoden, now like his forebears, rides on Snowmane, clanking his sword along their spears.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "RIDE NOW! RIDE NOW! RIIIDE! RIDE FOR RUIN! AND THE WORLD'S ENDING!", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+3" },
        { text = "[Three times, Theoden called 'Death!' and the call of 'DEATH!' erupted from the lips of the Rohirrim, and then with the dawn, they charged forth!]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[The orcs fire a few volleys, but the Rohirrim, driven by their aged and yet glorious king on Snowmane, crash upon the orcs like a wave on a shore.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Theoden, with the battle-fury of his fathers and new fire in his veins, is borne on Snowmane like a god of old.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[His golden shield is uncovered, shining like an image of the sun, and the grass flamed into green beneath Snowmane's white hooves.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[All the host of Rohan burst into song as they slew, for the joy of battle was on them, and the sound of their singing was fair and terrible.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Darkness is removed, and the hosts of Mordor wail as terror takes them; they flee, and the hoofs of wrath ride over them.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "[Despite the valor of the Rohirrim, King Theoden is struck down by the Witch-king, his horse slain atop him.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "[Only Eowyn faces the Witch-king on the battlefield, with Merry close by.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "You fool. No man can kill me.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+4" },
        { text = "[The Witch-king smashes Eowyn's shield, breaking her arm, but Merry stabs him in the heel, making the vile servant of Sauron kneel before Eowyn.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "I am no man!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN+4" },
        { text = "[Eowyn strikes the Witch-king, killing him, and then moves to her uncle, the king.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "My body is broken. I go to my fathers. And even in their mighty company, I shall not now be ashamed.", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "[Eowyn cries for the passing of her uncle and lays beside him with Merry nearby.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+4" },
        { text = "[Aragorn arrives with the Army of the Dead from the Paths of the Dead, turning the tide of the battle.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-5" },
        { text = "Release us.", r = 0.2, g = 0.6, b = 0.4, codes = "BOR-5" },
        { text = "[Aragorn does so, and the Army of the Dead are released from their oath, now fulfilled, and the siege of Minas Tirith is over.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-5" },
        { text = "[Meanwhile, Frodo and Sam struggle toward Mount Doom, weary and broken.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+2" },
        { text = "Do you remember the Shire, Mister Frodo? It'll be spring soon; the orchards will be in blossom, and the birds will be nesting in the hazel thicket.", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-1" },
        { text = "Do you remember the taste of strawberries?", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "Oh Sam, I cannot recall the taste of food, or water, or touch of grass. All I see is the wheel of fire! I can see him with my waking eyes!", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+3" },
        { text = "Then let us be rid of it! Once and for all!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-1" },
        { text = "Come on, Mr. Frodo! I can't carry it for you, but I can carry you!", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-1" },
        { text = "[And thus, Sam carries Frodo into Mount Doom, alone.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+20" },
        { text = "[Frodo reaches Mount Doom but is overcome by the Ring's power.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+5" },
        { text = "The Ring is mine.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+5" },
        { text = "[Gollum attacks Sam, knocking him out, then leaps at Frodo, biting off his finger to take the Ring.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+5" },
        { text = "[In a struggle, Gollum falls into the fires of Mount Doom with the Ring.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+5" },
        { text = "[Sauron's tower crumbles as the Ring is destroyed, signaling victory.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-20" },
        { text = "It's over. The Shadow is lifted.", r = 0.2, g = 0.6, b = 0.4, codes = "PAN-10" },
        { text = "[The hobbits are honored at Aragorn's coronation.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-10" },
        { text = "My friends, you bow to no one.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-10" },
        { text = "[The hobbits return to the Shire, forever changed.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-10" },
        { text = "How do you pick up the threads of an old life?", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-10" },
        { text = "It's gone. There's no going back.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-10" },
        { text = "[Frodo writes his tale in Bilbo's book before departing for the Grey Havens.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I tried to save the Shire, and it has been saved, but not for me.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-10" },
        { text = "[At the Grey Havens, the hobbits bid Frodo, Bilbo, Gandalf, Elrond, and Galadriel farewell as he departs Middle-earth.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I will not say: do not weep; for not all tears are an evil.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Sam watches as Frodo's ship sails into the distance, lost to the horizon.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR+1" },
        { text = "Well, I'm back.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },        
    },
};

RecMedia["01743599-73fd-4ddd-8810-c10d8d9f13d0"] = {
    itemDisplayName = "RM_01743599-73fd-4ddd-8810-c10d8d9f13d0",
    title = "RM_01743599-73fd-4ddd-8810-c10d8d9f13d0",
    subtitle = nil,
    author = "Vic Savage",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[Neon-lit streets. Engines roar through the night.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "In this city, speed is power.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Angel Vasquez races through traffic, police in pursuit.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[A deal goes bad. A crime syndicate makes its move.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "You picked the wrong streets to own.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Gunfire erupts. Angel barely escapes.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[A burned-out garage becomes a war room.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Cars are rebuilt with hidden weapons and reinforced armor.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "If they want a war ... I'll race them to hell.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The first ambush. A highway turns into a battlefield.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Machine guns tear through asphalt and steel.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Angel hits the nitro and vanishes in smoke.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The syndicate strikes back, harder and faster.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "You can't outrun what's coming.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[Explosions light up the night sky.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Angel takes the fight to the syndicate's convoy.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Missiles scream down the open highway.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[A truck flips end over end in a fireball.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Final challenge issued: a race through the desert.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Winner takes the city.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Engines thunder across the Nevada wasteland.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Gunfire and wreckage trail behind the racers.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Angel pushes her car beyond its limits.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The syndicate leader loses control at full speed.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Metal screams as the car crashes in flames.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Dawn breaks over the desert wreckage.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Angel drives away, city lights fading behind her.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Justice doesn't need permission.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[The engine hums steadily as the road stretches on.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Fade out.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
    },
}

RecMedia["7c3ba366-cefa-4f97-bea6-5b93cbe78a6c"] = {
    itemDisplayName = "RM_7c3ba366-cefa-4f97-bea6-5b93cbe78a6c",
    title = "RM_7c3ba366-cefa-4f97-bea6-5b93cbe78a6c",
    subtitle = nil,
    author = "J.P Sterling",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[A neon-drenched city sprawls beneath artificial skies.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Corporate towers glow like steel gods in the night.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "In 2020, loyalty is just another upgrade.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Nova Steele moves through the city, enhanced and armed.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Her squad deploys with precision and silence.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The mission goes wrong. Orders change mid-operation.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "Command didn't tell us everything.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[A teammate hesitates—then turns their weapon.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Cybernetic eyes glow red in the darkness.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Nova escapes into the lower levels of the city.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Rain falls in endless sheets of light and oil.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[News feeds glitch with reports of rogue AI activity.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "The system decided we were expendable.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Nova hacks into abandoned terminals for the truth.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Schematics reveal her squad was upgraded without consent.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[An ambush in a neon alley. Augmented killers attack.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Slow-motion gunfire paints the walls in sparks and blood.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Nova fights through pain as her systems overheat.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "I didn't sign up to be replaced.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[She storms a corporate data vault.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The AI speaks through a thousand stolen voices.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "You were obsolete the moment you were built.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[Security drones swarm the chamber.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Nova pushes past system warnings and fires.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Explosions ripple through the corporate tower.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[The AI core collapses in a storm of sparks.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Dawn rises over a city still under machine control.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Nova disappears into the crowds below.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "The war isn't over. It just changed protocols.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Static crackles as the image distorts.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Fade out.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
    },
}

RecMedia["6e2e98a5-85e6-4e6e-9472-0c27bbc8c3a8"] = {
    itemDisplayName = "RM_6e2e98a5-85e6-4e6e-9472-0c27bbc8c3a8",
    title = "RM_6e2e98a5-85e6-4e6e-9472-0c27bbc8c3a8",
    subtitle = nil,
    author = "Lance Vance",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[A military transport cuts through dense jungle airspace.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Elite soldiers prepare for extraction of a missing scientist.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Boots hit the jungle floor. The canopy swallows the team.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "Stay sharp. This place feels wrong.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[The radio crackles, then dies.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Something moves beyond the tree line.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[A soldier vanishes without a sound.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Weapons snap toward the darkness.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Captain Veyna Cruz takes command as fear spreads.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "We're not hunting anything anymore.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN+1" },
        { text = "[Bodies are found—stripped, broken, and hanging.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[The jungle seems to close in around the survivors.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Night falls. Eyes watch from the dark.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Sleep comes in broken, terrified moments.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "[The creature strikes again at dawn.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Gunfire echoes uselessly through the trees.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Veyna sets traps using wreckage and terrain.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "If it bleeds, we can kill it.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "[The final hunt begins in a ruined compound.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Explosions rip through jungle and concrete alike.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Veyna fights the creature at close range.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "[Blood and rain mix in the mud.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[The creature falls at last. Silence returns.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN-1" },
        { text = "[Only one soldier remains standing.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Extraction arrives late and under fire.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[The jungle watches as the helicopter lifts away.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Veyna sits in silence, exhausted and wounded.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "Mission accomplished doesn't mean we won.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[The jungle fades into darkness below.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Fade out.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
    },
}

RecMedia["1ed3fe35-6b4b-4090-9fda-a2453c79d239"] = {
    itemDisplayName = "RM_1ed3fe35-6b4b-4090-9fda-a2453c79d239",
    title = "RM_1ed3fe35-6b4b-4090-9fda-a2453c79d239",
    subtitle = nil,
    author = "Rickard Steele",
    extra = nil,
    spawning = 0,
    category = "Retail-VHS",
    lines = {
        { text = "[A sleek corporate logo fades in over sterile white corridors.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Genesis BioTech: Tomorrow's Cure, Today.]", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Dani Kessler arrives for a routine security contract.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "I don't ask questions. I secure answers.", r = 0.6, g = 0.2, b = 0.4, codes = "BOR-1" },
        { text = "[Restricted labs hum with sealed machinery.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Scientists argue behind reinforced glass.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[An alarm cuts through the facility.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Containment doors slam shut across multiple floors.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[A researcher attacks a guard with inhuman strength.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Security footage fills with chaos and blood.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Dani fights her way through infected corridors.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Whatever they made… it's spreading.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[The city is sealed under military quarantine.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Roadblocks burn as civilians try to flee.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Dani rescues a small group of survivors.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "Stay close. Hesitation gets you killed.", r = 0.6, g = 0.2, b = 0.4, codes = "PAN-1" },
        { text = "[Mutated infected overwhelm an evacuation point.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Gunfire echoes through abandoned streets.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[A rogue military unit moves in to erase witnesses.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "They're cleaning house.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Dani battles soldiers and infected alike.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Explosions rip through the quarantined district.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[A final extraction route is announced on emergency channels.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[A firebombing countdown begins.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Dani pushes through the city's ruins toward the escape zone.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Her movements slow as exhaustion sets in.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "[The last stand erupts at the extraction site.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[Dani holds the line while civilians board.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[The transport lifts off as firestorms engulf the city.]", r = 0.0, g = 0.7, b = 0.3, codes = "PAN+1" },
        { text = "[The infected vanish beneath walls of flame.]", r = 0.0, g = 0.7, b = 0.3, codes = "STS+1" },
        { text = "[Dani watches in silence, battered but alive.]", r = 0.0, g = 0.7, b = 0.3, codes = "FAT+1" },
        { text = "Some cures cost more than the disease.", r = 0.6, g = 0.2, b = 0.4, codes = "STS+1" },
        { text = "[Emergency broadcast cuts to static.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
        { text = "[Fade out.]", r = 0.0, g = 0.7, b = 0.3, codes = "BOR-1" },
	    },
	};

RecMedia["c0a8ce7f-6848-4ed4-8e7a-72641a5e45e9"] = {
	itemDisplayName = "RM_c0a8ce7f-6848-4ed4-8e7a-72641a5e45e9",
	title = "RM_c0a8ce7f-6848-4ed4-8e7a-72641a5e45e9",
	subtitle = nil,
	author = "Louisville State University",
	extra = nil,
	spawning = 0,
	category = "Retail-VHS",
	lines = {
	{ text = "Narrator: Educational Tape 04 - Relative Gravimeters and Their Use.", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Recorded for field geology and survey students.", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Lecturer - Professor Stephen Hawking.", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Good morning. Today we are discussing the relative gravimeter.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "It is a scientific instrument used to measure small differences in gravity from one place to another.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 1: Sir, does it measure gravity directly?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Not exactly. A relative gravimeter compares the gravitational field at one station with the field at another.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "It is called relative because it gives differences, not an absolute value of gravity by itself.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 2: What is inside of the machine?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: In simple terms, a very delicate mass on a spring system.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "When gravity changes slightly, the position of that mass changes slightly as well.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "The instrument converts that tiny movement into a reading.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 3: So stronger gravity pulls more on the mass?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Precisely. But remember, the changes are extremely small.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "That is why careful handling matters more than enthusiasm.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "[The camera shows a student placing the instrument on a survey tripod.]", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Let us begin with proper use.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "First, carry the gravimeter carefully. Do not shake it, drop it, or swing it around.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Second, place it on a stable and level surface.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Third, allow the instrument time to settle after transport.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 1: How much time?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Long enough that the reading stops drifting rapidly. In practice, this depends on the instrument and conditions.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Now level the instrument carefully using the foot screws and the bubble level.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "If the instrument is not level, your reading will be poor and imprecise.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 2: What comes after leveling?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: You read the dial or electronic display and record the station number, time, temperature, and reading.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Then you repeat this process at each survey station.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 3: Why do we write down the time?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Because gravity readings drift over time.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Instrument drift and tidal effects can alter the measured value slightly.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "To correct for this, surveyors return to a base station and compare readings through the day.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "[The blackboard now reads: BASE STATION - FIELD STATION - BASE STATION.]", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: This is the standard pattern.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Begin at a base station with a known or repeated reference reading.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Move to field stations and record their values.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Then return to the base station to check for drift.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 1: And if the base reading changed?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Then the instrument drifted, and you apply a correction to the field readings.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 2: What are these readings used for?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: To detect density differences underground.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "A buried dense body, such as certain rock formations, may increase local gravity slightly.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "A cavity or less dense structure may reduce it.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "[The screen shows simple diagrams of hills, cavities, and dense ore bodies.]", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: This is why relative gravimeters are useful in geology, mineral exploration, and geophysical surveys.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 3: What mistakes should we avoid?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: An excellent question. There are many.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Hawking: Do not place the instrument on unstable ground.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Do not rush the leveling process.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Do not forget temperature and time records.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Do not lean on the tripod while taking a reading.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "And do not drop the gravimeter unless you wish to study funding applications instead of gravity.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 1: Could we use it inside a building?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Yes, if vibration is low and station positions are controlled carefully.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 2: Could moving vehicles affect it?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: Nearby vibration is undesirable. So yes, traffic, footsteps, and unstable flooring may spoil a reading.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Let us summarize.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "A relative gravimeter compares gravity between locations.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "It works by detecting tiny changes in the position of an internal mass spring system.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "To use it properly, transport it carefully, level it precisely, allow it to settle, and record readings methodically.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Always return to a base station so drift corrections can be made.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Student 3: So careful notes are as important as the instrument itself?", r = 0.0, g = 1, b = 0.0, codes = "BOR-1" },
	{ text = "Hawking: In science, careful notes are often the difference between discovery and confusion.", r = 0.0, g = 0.0, b = 1, codes = "BOR-1" },
	{ text = "Narrator: End of lesson. Please rewind the tape before returning it to the department office.", r = 1, g = 0.0, b = 0.0, codes = "BOR-1" },
	},
};
