require "Items/WL_LootTableEditor"

local addLootItem = WL_LootTableEditor.addZombieLootItem
local addItem = WL_LootTableEditor.addItemToProceduralDistributions
local addMappedItem = WL_LootTableEditor.addItemToExistingDistribution

--- Fabric Glue
addItem("CrateLinens", "FabricGlue", 2)
addItem("MotelLinens", "FabricGlue", 2)
addItem("WardrobeMan", "FabricGlue", 2)
addItem("WardrobeManClassy", "FabricGlue", 2)
addItem("WardrobeWoman", "FabricGlue", 2)
addItem("WardrobeWomanClassy", "FabricGlue", 2)
addItem("WardrobeChild", "FabricGlue", 1)
addLootItem("Base.FabricGlue", 0.025)

--- ClipboardEmpty
addItem("ClassroomDesk", "ClipboardEmpty", 1)
addItem("MechanicShelfMisc", "ClipboardEmpty", 1)
addItem("FireDeptLockers", "ClipboardEmpty", 3)
addItem("LivingRoomShelf", "ClipboardEmpty", 3)
addItem("OfficeDesk", "ClipboardEmpty", 3)
addItem("OfficeDeskHome", "ClipboardEmpty", 3)
addItem("OfficeDeskDrawers", "ClipboardEmpty", 3)
addItem("OfficeShelves", "ClipboardEmpty", 3)
addItem("PoliceDesk", "ClipboardEmpty", 3)
addItem("PostOfficeMisc", "ClipboardEmpty", 3)
addItem("PostOfficeShelves", "ClipboardEmpty", 3)
addItem("PostOfficeCounter", "ClipboardEmpty", 3)
addItem("PostOfficeDesk", "ClipboardEmpty", 3)
addItem("DeskGeneric", "ClipboardEmpty", 3)
addItem("FancyOfficeDesk", "ClipboardEmpty", 3)

--- WIT_Pager
addItem("ClassroomDesk", "WIT_Pager", 1)
addItem("MechanicShelfMisc", "WIT_Pager", 1)
addItem("FireDeptLockers", "WIT_Pager", 3)
addItem("LivingRoomShelf", "WIT_Pager", 3)
addItem("OfficeDesk", "WIT_Pager", 3)
addItem("OfficeDeskHome", "WIT_Pager", 3)
addItem("OfficeDeskDrawers", "WIT_Pager", 3)
addItem("OfficeShelves", "WIT_Pager", 3)
addItem("PoliceDesk", "WIT_Pager", 3)
addItem("PostOfficeMisc", "WIT_Pager", 3)
addItem("PostOfficeShelves", "WIT_Pager", 3)
addItem("PostOfficeCounter", "WIT_Pager", 3)
addItem("PostOfficeDesk", "WIT_Pager", 3)
addItem("DeskGeneric", "WIT_Pager", 3)
addItem("FancyOfficeDesk", "ClipbWIT_PageroardEmpty", 3)
addItem("StoreShelfMedical", "WIT_Pager", 2)
addItem("MedicalClinicTools", "WIT_Pager", 1)
addLootItem("Base.WIT_Pager", 0.025)

--- UnwoundCassette
addItem("BandPracticeInstruments", "UnwoundCassette", 1)
addItem("CrateCompactDiscs", "UnwoundCassette", 1)
addItem("ElectronicStoreMusic", "UnwoundCassette", 1)
addItem("MusicStoreCDs", "UnwoundCassette", 1)
addItem("MusicStoreSpeaker", "UnwoundCassette", 1)
addItem("Hobbies", "UnwoundCassette", 1)
addItem("BedroomDresser", "UnwoundCassette", 2)
addItem("BedroomSideTable", "UnwoundCassette", 2)
addItem("ClosetShelfGeneric", "UnwoundCassette", 1)
addItem("DresserGeneric", "UnwoundCassette", 2)
addItem("LivingRoomShelf", "UnwoundCassette", 2)
addItem("LivingRoomShelfNoTapes", "UnwoundCassette", 1)
addItem("LivingRoomSideTable", "UnwoundCassette", 2)
addItem("LivingRoomSideTableNoRemote", "UnwoundCassette", 2)
addItem("ShelfGeneric", "UnwoundCassette", 1)
addItem("WardrobeChild", "UnwoundCassette", 2)
addItem("WardrobeMan", "UnwoundCassette", 2)
addItem("WardrobeManClassy", "UnwoundCassette", 2)
addItem("WardrobeRedneck", "UnwoundCassette", 2)
addItem("WardrobeWoman", "UnwoundCassette", 2)
addItem("WardrobeWomanClassy", "UnwoundCassette", 2)
addItem("DeskGeneric", "UnwoundCassette", 1)
addItem("FactoryLockers", "UnwoundCassette", 1)
addItem("FireDeptLockers", "UnwoundCassette", 1)
addItem("GymLockers", "UnwoundCassette", 2)
addItem("HospitalLockers", "UnwoundCassette", 1)
addItem("Locker", "UnwoundCassette", 2)
addItem("LockerClassy", "UnwoundCassette", 1)
addItem("OfficeDesk", "UnwoundCassette", 2)
addItem("OfficeDeskHome", "UnwoundCassette", 2)
addItem("OfficeDrawers", "UnwoundCassette", 2)
addItem("PoliceDesk", "UnwoundCassette", 1)
addItem("PoliceLockers", "UnwoundCassette", 1)
addItem("SchoolLockers", "UnwoundCassette", 2)
addItem("SecurityLockers", "UnwoundCassette", 1)
addItem("FitnessTrainer", "UnwoundCassette", 1)
addItem("Gifts", "UnwoundCassette", 2)
addItem("GolfLockers", "UnwoundCassette", 1)
addItem("HolidayStuff", "UnwoundCassette", 1)
addLootItem("Base.UnwoundCassette", 0.01)

--- Damage Blueprints
addMappedItem("NailsBox", "Base.BlueprintPackGeneral", 0.25, false, false)
addMappedItem("WIT_Pager", "Base.BlueprintPackGeneral", 0.5, false, false)
addLootItem("Base.BlueprintPackGeneral", 0.00025)