require 'Items/ProceduralDistributions'

for _, category in pairs(ProceduralDistributions.list) do
    for i, v in ipairs(category.items) do
        if v == "Padlock" then
            category.items[i] = "WLLPadlock"
        end
    end
end

local function addItemToDist(category, item, chance)
    table.insert(ProceduralDistributions.list[category].items, item)
    table.insert(ProceduralDistributions.list[category].items, chance)
end

local function addLocksToDist(category, chance)
    addItemToDist(category, "WLLPadlock", chance)
    addItemToDist(category, "WLLCombinationPadlock", chance)
end

addLocksToDist("ArmyHangarTools", 1)
addLocksToDist("ArmySurplusMisc", 1)
addLocksToDist("BarCounterMisc", 1)
addLocksToDist("BathroomCabinet", 0.2)
addLocksToDist("BathroomCounter", 0.5)
addLocksToDist("BathroomCounterNoMeds", 0.2)
addLocksToDist("BedroomDresser", 0.2)
addLocksToDist("BurglarTools", 1)
addLocksToDist("CabinetFactoryTools", 3)
addLocksToDist("CampingLockers", 0.5)
addLocksToDist("CampingStoreGear", 2)
addLocksToDist("CarSupplyTools", 0.2)
addLocksToDist("ClassroomDesk", 1)
addLocksToDist("ClassroomMisc", 0.2)
addLocksToDist("ClosetShelfGeneric", 0.5)
addLocksToDist("ControlRoomCounter", 0.2)
addLocksToDist("CrateCamping", 2)
addLocksToDist("CrateCarpentry", 1)
addLocksToDist("CrateMetalwork", 1)
addLocksToDist("CrateOfficeSupplies", 1)
addLocksToDist("CrateRandomJunk", 0.5)
addLocksToDist("DaycareDesk", 0.1)
addLocksToDist("DaycareShelves", 0.1)
addLocksToDist("DeskGeneric", 1)
addLocksToDist("DresserGeneric", 0.01)
addLocksToDist("DrugShackMisc", 5)
addLocksToDist("EngineerTools", 1)
addLocksToDist("FactoryLockers", 3)
addLocksToDist("FilingCabinetGeneric", 1)
addLocksToDist("FireDeptLockers", 2)
addLocksToDist("FireStorageTools", 1)
addLocksToDist("GarageCarpentry", 2)
addLocksToDist("GarageMetalwork", 1)
addLocksToDist("GarageTools", 1)
addLocksToDist("GardenStoreTools", 1)
addLocksToDist("GeneratorRoom", 1)
addLocksToDist("GigamartSchool", 1)
addLocksToDist("GigamartTools", 1)
addLocksToDist("GymLockers", 0.01)
addLocksToDist("Hiker", 0.2)
addLocksToDist("HospitalLockers", 1)
addLocksToDist("HuntingLockers", 0.02)
addLocksToDist("JanitorMisc", 1)
addLocksToDist("JanitorTools", 1)
addLocksToDist("KitchenRandom", 1)
addLocksToDist("Locker", 1)
addLocksToDist("LockerArmyBedroom", 1)
addLocksToDist("LockerClassy", 1)
addLocksToDist("LoggingFactoryTools", 1)
addLocksToDist("MechanicShelfTools", 1)
addLocksToDist("OfficeCounter", 0.01)
addLocksToDist("OfficeDesk", 0.01)
addLocksToDist("OfficeDeskHome", 1)
addLocksToDist("OtherGeneric", 0.01)
addLocksToDist("PoliceDesk", 1)
addLocksToDist("PoliceLockers", 2)
addLocksToDist("PrisonGuardLockers", 1)
addLocksToDist("RandomFiller", 0.01)
addLocksToDist("SchoolLockers", 8)
addLocksToDist("SecurityLockers", 5)
addLocksToDist("StoreShelfMechanics", 0.1)
addLocksToDist("ToolStoreCarpentry", 1)
addLocksToDist("ToolStoreMisc", 1)
addLocksToDist("WardrobeMan", 0.1)
addLocksToDist("WardrobeManClassy", 0.1)
addLocksToDist("WardrobeRedneck", 0.01)
addLocksToDist("WardrobeWoman", 0.1)
addLocksToDist("WardrobeWomanClassy", 0.1)

addItemToDist("BurglarTools", "WLLDoorLock", 0.2)
addItemToDist("CabinetFactoryTools", "WLLDoorLock", 1)
addItemToDist("GarageCarpentry", "WLLDoorLock", 1)
addItemToDist("JanitorMisc", "WLLDoorLock", 0.5)
addItemToDist("JanitorTools", "WLLDoorLock", 0.5)
addItemToDist("ToolStoreMisc", "WLLDoorLock", 0.5)
